differentiate subl plugin depending on log level

diff --git a/Config/plugins/subl/uninstall b/Config/plugins/subl/uninstall
--- a/Config/plugins/subl/uninstall
+++ b/Config/plugins/subl/uninstall
@@ -1,14 +1,20 @@
+#!/bin/zsh
+source $WS_CFG_PATH/ws-shared
 source ./shared
 
 # remove keymap
 #if [ -h "$subl_config_path/$subl_keymap_name" ]; then
 if [ -e "$subl_config_path/$subl_keymap_name" ]; then
-	echo "creating backup for '$subl_keymap_name' ..."
-	cp -Rav "$subl_config_path/$subl_keymap_name" "$subl_config_path/$subl_keymap_name.$(date_timestamp_name).bak"
-	echo "removing origin '$subl_keymap_name' in '$subl_config_path' ..."
+	_ws_log verbose "creating backup for '$subl_keymap_name' ..."
+	CPFLAGS=-Ra
+	if _ws_should_log verbose; then
+		CPFLAGS+=v
+	fi
+	cp $CPFLAGS "$subl_config_path/$subl_keymap_name" "$subl_config_path/$subl_keymap_name.$(date_timestamp_name).bak"
+	_ws_log verbose "removing origin '$subl_keymap_name' in '$subl_config_path' ..."
 	rm "$subl_config_path/$subl_keymap_name"
 	exit 0
 else
-	echo "Keyfile is missing! ($subl_config_path/$subl_keymap_name)" >&2
+	_ws_log error "Keyfile is missing! ($subl_config_path/$subl_keymap_name)" >&2
 	exit 1
 fi
